// Generate a deterministic source map from module exports and existing comments.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const sourceRoot = join(root, 'src');
const groups = new Map();
const cell = (value) => String(value).replaceAll('|', '\\|').replace(/[\r\n]+/g, ' ');

function walk(directory) {
  for (const entry of readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name, 'en'))) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) walk(path);
    else if (entry.isFile() && /\.(?:js|sql)$/.test(entry.name)) {
      const source = readFileSync(path, 'utf8');
      const location = relative(root, path).split('\\').join('/');
      const directoryName = dirname(location);
      const exports = [...source.matchAll(/^export\s+(?:async\s+)?(?:function|const|class)\s+(\w+)/gm)].map(match => match[1]);
      const firstComment = source.split(/\r?\n/).map(line => line.trim()).find(line => /^(?:\/\/|\/\*\*?|--)(?:\s|$)/.test(line));
      const purpose = firstComment?.replace(/^(?:\/\/|\/\*\*?|--)\s*/, '').replace(/\s*\*\/$/, '') || '—';
      const lines = source ? source.replace(/\r?\n$/, '').split(/\r?\n/).length : 0;
      if (!groups.has(directoryName)) groups.set(directoryName, []);
      groups.get(directoryName).push(`| [${entry.name}](${location}) | ${lines} | ${exports.length ? exports.map(name => `\`${name}\``).join(', ') : '—'} | ${cell(purpose)} |`);
    }
  }
}

walk(sourceRoot);
const sections = [...groups].sort(([left], [right]) => left.localeCompare(right, 'en')).map(([directory, rows]) =>
  `## ${directory}\n\n| File | Lines | Exports | First comment |\n| --- | ---: | --- | --- |\n${rows.join('\n')}`);
const content = `# CareOps code map\n\nAuto-generated by \`npm run codemap\`. Source files under \`src/\`; exports use a lightweight declaration scan, and the final column is the first existing comment, not an inferred description.\n\nStart with [ARCHITECTURE.md](ARCHITECTURE.md) for the request flow and [docs/API.md](docs/API.md) for endpoints. Frontend pages live in \`web/\`, synthetic data in \`seed/\`, and validation in \`tests/\` and \`e2e/\`.\n\n${sections.join('\n\n')}\n`;
writeFileSync(join(root, 'CODEMAP.md'), content);
console.log(`Wrote CODEMAP.md (${[...groups.values()].reduce((sum, rows) => sum + rows.length, 0)} source files).`);
